### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by zhmz90** [OpenGene/CtDNASomaticVariantSimulator.jl#1]
Total time budget: 1 week
- [ ] with BAMSurgeon and gDNA data, simulate tumor data and compare accuracy among different variant callers such as Varscan2, Mutect, RAID, Strela, SomaticSnipper, bcbio-nextgen.  [Tue-Wed]
- [ ] simuate cfDNA and compare accuracy again [Tur]
- [ ] First version of ML based variant caller try to beat others. [Fri-Mon-Tue]
